export { BookingStatus, PaymentMethod, PaymentStatus } from '@prisma/client';

export const ALLOWED_TRANSITIONS: Record<string, string[]> = {
  REQUESTED: ['SEARCHING_DRIVER', 'CANCELLED'],
  SEARCHING_DRIVER: ['DRIVER_ASSIGNED', 'CANCELLED'],
  DRIVER_ASSIGNED: ['DRIVER_ARRIVING', 'CANCELLED'],
  DRIVER_ARRIVING: ['DRIVER_ARRIVED', 'CANCELLED'],
  DRIVER_ARRIVED: ['TRIP_STARTED', 'CANCELLED'],
  TRIP_STARTED: ['TRIP_COMPLETED'],
  TRIP_COMPLETED: ['PAYMENT_PENDING'],
  PAYMENT_PENDING: ['COMPLETED'],
  COMPLETED: [],
  CANCELLED: [],
};

export const CANCELLABLE_STATUSES = [
  'REQUESTED',
  'SEARCHING_DRIVER',
  'DRIVER_ASSIGNED',
  'DRIVER_ARRIVING',
  'DRIVER_ARRIVED',
];
